name: tariff_hedge_sim
version: "1.0.0"
config-version: 2

profile: tariff_hedge_sim

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  tariff_hedge_sim:
    staging:
      +materialized: view
    silver:
      +materialized: table
    gold:
      +materialized: table
